# Definitions of Data Science

Naur \| US \| 1971

:   The starting point is the concept of *data*, as defined in \[0.7\]: DATA: *A representation of facts or ideas in a formalized manner capable of being communicated or manipulated by some process.* Data science is the science of dealing with data, once they have been established, while the relation of data to what they represent is delegated to other fields and sciences.  \
    \
    The usefulness of data and data processes derives from their application in building and handling models of reality.  \
    ...\
    A basic principle of data science is this: The data representation must be chosen with due regard to the transformation to be achieved and the data processing tools available. This stresses the importance of concern for the characteristics of the data processing tools.\
    \
    Limits on what may be achieved by data processing may arise both from the difficulty of establishing data that represent a field of interest in a relevant manner, and from the difficulty of formulating the data processing needed. Some of the difficulty of understanding these limits is caused by the ease with which certain data processing tasks are performed by humans [@naur1974: 30-31; emphasis and citation in original; the reference "0.7" refers to @ifipgui1971].

    Pull quote: "Data science is the science of dealing with data, once they have been established."

    Comment: Note separation from "establishment," which is conduct by science proper.

Hayashi \| Japan \| 1996

:   Data science is not only a synthetic concept to unify \[mathematical\] statistics, data analysis and their related methods but also comprises their results. It includes three phases, design for data, collection of data, and analysis on data. Data science intends to analyze and understand actual phenomena with "data." In other words, the aim of data science is to reveal the features of the hidden structure of complicated natural, human and social phenomena with data from a different point of view from the established or traditional theory and method. This point of view implies multidimensional, dynamic and flexible ways of thinking [@hayashi1998: 41].

    Pull quote: "... the aim of data science is to reveal the features of the hidden structure of complicated natural, human and social phenomena with data from a different point of view from the established or traditional theory and method. This point of view implies multidimensional, dynamic and flexible ways of thinking."

    Comment: Note the similarity to DSL's concept of dynamic data processing. Also note the difference to Naur's definition. Hayashi includes design for data and its collection, fundamental scientific activities. This is reflective of the statistician's approach, which seeks to participate in the scientific activity of generating data.

CODATA \| US \| 2002

:   See editorial.

NSF \| US \| 2005

:   Quote report in full. Don't forget this nugget: "Research insights can arise from the deep understanding of the data scientist of the fundamental nature of the representation. Such insights complement the insights of the domain expert. As a result, data scientists sometimes are primary contributors to research progress."

JISC \| UK \| 2008

:   Data scientist: people who work where the research is carried out---or, in the case of data centre personnel, in close collaboration with the creators of the data---and may be involved in creative enquiry and analysis, enabling others to work with digital data, and developments in data base technology

Hal Varian \| US \| 2008 \| implied

:   I think statisticians are part of it, but it's just a part. *You also want to be able to visualize the data, communicate the data, and utilize it effectively*. But I do think those skills---of being able to access, understand, and communicate the insights you get from data analysis---are going to be extremely important. Managers need to be able to access and understand the data themselves [@mckinseycompany2009; emphases added].

Yau \| US \| 2008

:   Summarize blog posts.

Mason and Wiggins \| US \| 2008

:   Get quote.

Conway \| US \| 2010

:   Summarize diagram; get quote from original article.

Loukides \| US \| 2011

:   Data science enables the creation of data products [@loukides2011].

HBR \| US \| 2012

:   Data scientists as those who "make discoveries while swimming in \[the deluge of\] data," "bring structure to large quantities of formless data and make analysis possible," "identify rich data sources, join them with other, potentially incomplete data sources, and cleaning the resulting set," "help decision makers shift from ad hoc analysis to an ongoing conversation with data," "are creative in displaying information visually and making the patterns they find clear and compelling," and "advise executives and product managers on the implications of the data for products, processes, and decisions'" [@davenportDataScientistSexiest2012].


Zhu, Yangyong, and Yun Xiong. 2015. “Defining Data Science.” arXiv:1501.05039 [Cs], January. http://arxiv.org/abs/1501.05039.


EDISON Data Science Framework \| Europe \| 2017

:   Data Science is the extraction of actionable knowledge directly from data through a process of discovery, or hypothesis formulation and hypothesis testing. It can also be understood as the activities happening in the processing layer of the system architecture, against data stored in the data layer, in order to extract knowledge from the raw data [@demchenko2017a: 8].