project:
  title: "The Transformation of Data Science"
  type: book
  output-dir: docs  

book:
  title: "The Transformation of Data Science"
  author: "Rafael C. Alvarado"
  page-navigation: true  
  date: "10/11/2023"

  chapters:
  - index.qmd                                # Abstract
  
  - part: "Overview"
    chapters:
    - chapters/01-history-introduction.qmd   # Introduction
    - chapters/history-method.qmd            # Method
    # Review
  
  - part: "Evidence"
    chapters:                         
    - chapters/02-history-1960s.qmd          # Origins
    - chapters/03-history-1970s-and-80s.qmd  # Classical DS
    - chapters/04-history-1990s.qmd          # Statistics Disrupted
    - chapters/05-history-2000s.qmd          # Data Science Grows
    - chapters/06-history-2008-2012.qmd      # The Sexy Science
    - chapters/07-history-disconnect.qmd     # The Disconnect
  
  - part: "Interpretation"
    chapters:
    - chapters/00-synopsis.qmd               # Synopsis    
    - chapters/08-history-interpretation.qmd # Conclusion
  
  - references.qmd
  # appendices:
  # - chapters/history-method.qmd
  
page-footer:
  left: |
    Written by Rafael C. Alvarado with input from many colleagues at UVA's [School of Data Science](http://datascience.virginia.edu).
  right: |
    This book was built with <a href="https://quarto.org/">Quarto</a>.


bibliography: bib/references.bib

format:
  html:
    theme: [cosmo, default.css]
  # pdf:
  #   documentclass: scrreprt

  # pdf:
  #   documentclass: report
  #   include-in-header: 
  #     text: |
  #       \usepackage{makeidx}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex


